---
functional:
  - Пользователь может зарегистрироваться на сайте заполнив данные в форме регистрации
  - Пользователь может авторизоваться на сайте через логин/пароль
  - Пользователь может зарегистрироваться/авторизоваться на сайте через аккаунт Github или Discord
  - Пользователь может создать игру или присоединиться к игре с ботом или другим пользователем
  - При создании игры пользователь может настраивать условия игры (сложность, выбрать соперника, время, тип задачи)
  - Пользователь может создать ссылку-приглашение к созданной им игре
  - В процессе игры пользователь может просматривать задание на двух языках — русском и английском
  - В процессе игры пользователь видит код соперника
  - В процессе игры пользователь может менять язык программирования
  - Другие пользователи могут следить за ходом игр в качестве наблюдателя
  - Пользователь имеет доступ в чат для общения с другими пользователями
  - Пользователь может написать личное сообщение другому пользователю
  - Пользователь может просматривать и настраивать свой профиль
  - Пользователь может просматривать результаты завершенных игр
  - Незарегистрированный пользователь может создать тестовую игру без регистрации
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - В форме регистрации система проверяет введенные данные на логику (Имя, почта, пароль)
  - Корректное масштабирование всех элементов на странице при любом выбранном масштабе.

